version: '3'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'sandbox'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
volumes:
  mysql:
    driver: local